version: '3'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ../../:/workspaces:cached
    tty: true

  proxy:
    build:
      context: .
      dockerfile: dockerfile.proxy
    ports:
      - 80:80